// Code generated by goctl. DO NOT EDIT.

import { instance as http } from "./apiRequester"
import { AxiosRequestConfig } from "axios"
import qs from "qs"
import * as components from "./demoComponents"
export * from "./demoComponents"

/**
 * @description 
 */
export function nothing(config?: AxiosRequestConfig) {
  return http.get<null>(`/`, config)
}

/**
 * @description "错误响应实例"
 * @param req
 */
export function demoError(req: components.DemoError_Request, config?: AxiosRequestConfig) {
  return http.post<components.DemoError_Response>(`/demo/error`, req, config)
}

/**
 * @description "文档"
 */
export function swaggerDoc(config?: AxiosRequestConfig) {
  return http.get<null>(`/doc/swagger`, config)
}

/**
 * @description 获取登录图形验证码
 */
export function admin_public_getSignInCaptcha(config?: AxiosRequestConfig) {
  return http.get<components.Admin_Public_GetSignInCaptcha_Response>(`/admin/public/sign-in/captcha`, config)
}

/**
 * @description 校验登录图形验证码
 */
export function admin_public_checkSignInCaptcha(config?: AxiosRequestConfig) {
  return http.post<components.Admin_Public_CheckSignInCaptcha_Response>(`/admin/public/sign-in/check-captcha`, config)
}

/**
 * @description 账号登录
 * @param req
 */
export function admin_public_signInAccount(req: components.Admin_Public_SignInAccount_Request, config?: AxiosRequestConfig) {
  return http.post<components.Admin_Public_SignInAccount_Response>(`/admin/public/sign-in/account`, req, config)
}

/**
 * @description 手机登录
 * @param req
 */
export function admin_public_signInMobile(req: components.Admin_Public_SignInMobile_Request, config?: AxiosRequestConfig) {
  return http.post<components.Admin_Public_SignInMobile_Response>(`/admin/public/sign-in/mobile`, req, config)
}

/**
 * @description 发送登录短信验证码
 * @param req
 */
export function admin_public_sendSignInSMS(req: components.Admin_Public_SendSignInSMS_Request, config?: AxiosRequestConfig) {
  return http.patch<components.Admin_Public_SendSignInSMS_Response>(`/admin/public/sign-in/send-sms`, req, config)
}

/**
 * @description 获取注册图形验证码
 */
export function user_public_getSignUpCaptcha(config?: AxiosRequestConfig) {
  return http.get<components.User_Public_GetSignUpCaptcha_Response>(`/user/public/sign-up/captcha`, config)
}

/**
 * @description 校验注册图形验证码
 */
export function user_public_checkSignUpCaptcha(config?: AxiosRequestConfig) {
  return http.patch<components.User_Public_CheckSignUpCaptcha_Response>(`/user/public/sign-up/check-captcha`, config)
}

/**
 * @description 账号注册
 * @param req
 */
export function user_public_signUpAccount(req: components.User_Public_SignUpAccount_Request, config?: AxiosRequestConfig) {
  return http.post<components.User_Public_SignUpAccount_Response>(`/user/public/sign-up/account`, req, config)
}

/**
 * @description 手机注册
 * @param req
 */
export function user_public_signUpMobile(req: components.User_Public_SignUpMobile_Request, config?: AxiosRequestConfig) {
  return http.post<components.User_Public_SignUpMobile_Response>(`/user/public/sign-up/mobile`, req, config)
}

/**
 * @description 发送注册短信验证码
 * @param req
 */
export function user_public_sendSignUpSMS(req: components.User_Public_SendSignUpSMS_Request, config?: AxiosRequestConfig) {
  return http.patch<components.User_Public_SendSignUpSMS_Response>(`/user/public/sign-up/send-sms`, req, config)
}

/**
 * @description 获取登录图形验证码
 */
export function user_public_getSignInCaptcha(config?: AxiosRequestConfig) {
  return http.get<components.User_Public_GetSignInCaptcha_Response>(`/user/public/sign-in/captcha`, config)
}

/**
 * @description 校验登录图形验证码
 */
export function user_public_checkSignInCaptcha(config?: AxiosRequestConfig) {
  return http.post<components.User_Public_CheckSignInCaptcha_Response>(`/user/public/sign-in/check-captcha`, config)
}

/**
 * @description 账号登录
 * @param req
 */
export function user_public_signInAccount(req: components.User_Public_SignInAccount_Request, config?: AxiosRequestConfig) {
  return http.post<components.User_Public_SignInAccount_Response>(`/user/public/sign-in/account`, req, config)
}

/**
 * @description 手机登录
 * @param req
 */
export function user_public_signInMobile(req: components.User_Public_SignInMobile_Request, config?: AxiosRequestConfig) {
  return http.post<components.User_Public_SignInMobile_Response>(`/user/public/sign-in/mobile`, req, config)
}

/**
 * @description 发送登录短信验证码
 * @param req
 */
export function user_public_sendSignInSMS(req: components.User_Public_SendSignInSMS_Request, config?: AxiosRequestConfig) {
  return http.patch<components.User_Public_SendSignInSMS_Response>(`/user/public/sign-in/send-sms`, req, config)
}

/**
 * @description 安全退出
 */
export function user_self_signOut(config?: AxiosRequestConfig) {
  return http.post<components.User_Self_SignOut_Response>(`/user/self/sign-out`, config)
}

/**
 * @description 修改密码
 * @param req
 */
export function user_self_editPassword(req: components.User_Self_EditPassword_Request, config?: AxiosRequestConfig) {
  return http.put<components.User_Self_EditPassword_Response>(`/user/self/password`, req, config)
}

/**
 * @description 获取列表
 * @param query
 */
export function user_self_foodList(query: components.User_Self_FoodList_RequestParams, config?: AxiosRequestConfig) {
  return http.get<components.User_Self_FoodList_Response>(`/user/self/foods` + `?` + qs.stringify(query), config)
}

/**
 * @description 获取详情
 */
export function user_self_foodItem(id: number, config?: AxiosRequestConfig) {
  return http.get<components.User_Self_FoodItem_Response>(`/user/self/foods/${id}`, config)
}

/**
 * @description 新增
 * @param req
 */
export function user_self_foodCreate(req: components.User_Self_FoodCreate_Request, config?: AxiosRequestConfig) {
  return http.post<components.User_Self_FoodCreate_Response>(`/user/self/foods`, req, config)
}

/**
 * @description 编辑
 * @param req
 */
export function user_self_foodEdit(req: components.User_Self_FoodEdit_Request, id: number, config?: AxiosRequestConfig) {
  return http.put<components.User_Self_FoodEdit_Response>(`/user/self/foods/${id}`, req, config)
}

/**
 * @description 批量删除
 * @param query
 */
export function user_self_foodDelete(query: components.User_Self_FoodDelete_RequestParams, config?: AxiosRequestConfig) {
  return http.delete<components.User_Self_FoodDelete_Response>(`/user/self/foods` + `?` + qs.stringify(query), config)
}

/**
 * @description 补充食材
 * @param req
 */
export function user_self_foodIncrease(req: components.User_Self_FoodIncrease_Request, id: number, config?: AxiosRequestConfig) {
  return http.patch<components.User_Self_FoodIncrease_Response>(`/user/self/foods/${id}/increase`, req, config)
}

/**
 * @description 消耗食材
 * @param req
 */
export function user_self_foodDecrease(req: components.User_Self_FoodDecrease_Request, id: number, config?: AxiosRequestConfig) {
  return http.patch<components.User_Self_FoodDecrease_Response>(`/user/self/foods/${id}/decrease`, req, config)
}
